-- PostgreSQL edition of db/escalated/mysql/V6__create_escalated_skill_routing_departments.sql.
-- The two are one migration: change them together, never one alone.

CREATE TABLE escalated_skill_routing_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_escalated_skill_routing_departments_skill_dept UNIQUE (skill_id, department_id),
    CONSTRAINT fk_escalated_skill_routing_departments_skill FOREIGN KEY (skill_id) REFERENCES escalated_skills (id) ON DELETE CASCADE,
    CONSTRAINT fk_escalated_skill_routing_departments_department FOREIGN KEY (department_id) REFERENCES escalated_departments (id) ON DELETE CASCADE
);
